import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "@/components/btClient/BootstrapClient";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { Inter } from 'next/font/google';
import './globals.css';
import styles from "./page.module.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/components/AuthProvider/AuthProvider";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Krona+One&family=Kufam&display=swap" rel="stylesheet" />
      </head>
      <body className={styles.bd} >
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
          <BootstrapClient />
        </AuthProvider>
      </body>
    </html>
  )
}
